language: cpp

compiler:
 - clang
 - gcc

before_build:
    - mkdir build
    - cd build
    - cmake ../test/ --target Test

script: make

notifications:
  slack: imminfo:CJCtbSdFOW1w9xMoY0HxSLgY
  email: false