language: cpp

python:
 - "3.4"

compiler:
 - clang
 - gcc

before_install:
 - curl -sL https://github.com/open-source-parsers/jsoncpp/archive/master.zip > jsoncpp.zip
 - unzip jsoncpp.zip
 - rm jsoncpp.zip
 - cd jsoncpp-master
 - python amalgamate.py
 - mv ./dist/jsoncpp.cpp ../src/jsoncpp.cpp
 - mv ./dist/json ../include/json
 - cd ..
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
 - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build .
 - python3 pyymir.py

after_success:
 - ls ./build
 - ./build/test

notifications:
  slack: imminfo:CJCtbSdFOW1w9xMoY0HxSLgY
  email: false