language: cpp

compiler:
 - clang
 - gcc

script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . --target Test

notifications:
  slack: imminfo:CJCtbSdFOW1w9xMoY0HxSLgY
  email: false