site_name: Ymir
site_url: https://imminfo.github.io/ymir/
repo_url: https://github.com/imminfo/ymir/
site_author: Vadim Nazarov
copyright: Copyright © 2015 Vadim Nazarov.
pages:
- 'Home' : 'index.md'
- 'Algorithms' : 'algorithms.md'
- 'C++ Reference' : 'api.md'
- 'R package' : 'rpackage.md'
- 'About' : 'about.md'
- 'Immunoinformatics page' : 'mainpage.md'
theme: yeti
#theme: readthedocs